import "./globals.css";
import type { Metadata } from "next";
import { ConfigProvider } from "antd";
import NextAuthSessionProvider from "@/providers/authProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConfigProvider
      theme={{
        token: {
          // Seed Token
          // colorPrimary: "#00b96b",
          borderRadius: 4,
          fontFamily: "Roboto",
          fontSize: 16,
        },
      }}
    >
      <html lang="en">
        <body>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </body>
      </html>
    </ConfigProvider>
  );
}
